### ISSUE TITLE
Documenting dependencies version

### ISSUE THREAD

**Issue by skanwal** [c-BIG/wgs-sample-qc#4]
Hello,

We ([@UMCCR](https://mdhs.unimelb.edu.au/centre-for-cancer-research)) are trying to incorporate your [calculate_coverage.py](https://github.com/c-BIG/wgs-sample-qc/blob/main/example_implementations/sg-npm/calculate_coverage.py) script as a step in our CWL workflow as part of GHIF-QC project. 

To help us compile dependencies of this script in a docker container, can you please include version of the programs listed in [README.md](https://github.com/c-BIG/wgs-sample-qc/tree/main/example_implementations/sg-npm#readme)?

At this point, I have noted following issues:
- `bedtools` is not listed as a dependency.
- `datamash` version available via conda is `v1.1.0`. This version complains (`unrecognized option '--round') as referenced in the script. It could be a version conflict issue.

This will be appreciated.

**Comment by skanwal** [comment]
Quick update:

Got the script working with `datamash - v1.7`.
I had to make two updates in the script at https://github.com/skanwal/wgs-sample-qc/blob/main/calculate_coverage.py#L159 and https://github.com/skanwal/wgs-sample-qc/blob/main/calculate_coverage.py#L169 as I was getting following issue:

```
ValueError: invalid literal for int() with base 10: '2.68168e+09'
```
A bit of google search pointed me to https://careerkarma.com/blog/python-valueerror-invalid-literal-for-int-with-base-10/

```
The Python ValueError: invalid literal for int() with base 10 error is raised when you try to convert a string value that is not formatted as an integer.

To solve this problem, you can use the float() method to convert a floating-point number in a string to an integer. Then, you can use int() to convert your number to an integer.
```

Wanted to mention it here just in case you've experienced it as well or think this might be due to another issue/conflict.

**Comment by mgonzalezporta** [comment]
Hi,

Apologies for the delay, only noticed this issue in our latest GHIF meeting. I've updated the README accordingly to make it more explicit about the dependencies of the script. The right solution here is to provide a docker container - this is what we have for our full QC pipeline, and what we're aiming to release as our final reference implementation.

Let me know if there are any pending queries in the meantime.

Mar

**Comment by skanwal** [comment]
Thanks for the response, Mar.

> The right solution here is to provide a docker container

Do you have a public image that you're using in your full QC pipeline? 

Also, wondering if you'v seen the `ValueError` issue I have linked in my last message?

**Comment by mgonzalezporta** [comment]
Yes, you can find the image definition here: https://github.com/c-BIG/NPM-sample-qc/tree/master/containers

Regarding the `ValueError`, I don't recall encountering that. Could it be related to the Python version?

**Comment by skanwal** [comment]
Not sure - my python version is `Python 3.9.5`. I noted yours is `3.7` in the conda envm file at https://github.com/c-BIG/NPM-sample-qc/tree/master/containers.
